In [1]:
from bs4 import BeautifulSoup
import requests as r

In [10]:
url = "https://en.wikipedia.org/wiki/Roger_Federer_career_statistics"

In [ ]:
page = r.get(url)

In [15]:
soup = BeautifulSoup(page.text,'html')

In [ ]:
print(soup.prettify())

In [ ]:
soup.find('table',class_ ="wikitable nowrap")

In [ ]:
table = soup.find_all('table')[2]
table

In [87]:
table_singles= table.find_all('th')

In [ ]:
table_singles

In [ ]:
titles_singles_table = [title.text.strip() for title in table_singles]
titles_singles_table

In [68]:
import pandas as pd

In [98]:
df =pd.DataFrame(columns = titles_singles_table)
df

Empty DataFrame
Columns: [Tournament, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, SR, W–L, Win %, , 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, SR, W–L, Win %]
Index: []

[0 rows x 56 columns]

In [ ]:
column_data_table_singles = table.find_all('tr')
column_data_table_singles

In [123]:

for row in column_data_table_singles[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]
    
    # Asegurarse de que la longitud de individual_row_data coincida con el número de columnas
    if len(individual_row_data) < len(df.columns):
        # Si la longitud es menor, rellenar con valores vacíos
        individual_row_data.extend([''] * (len(df.columns) - len(individual_row_data)))
    elif len(individual_row_data) > len(df.columns):
        # Si la longitud es mayor, recortar la lista a la longitud correcta
        individual_row_data = individual_row_data[:len(df.columns)]
    
    df.loc[len(df)] = individual_row_data

df

,Tournament,1998,1999,2000,2001,2002,2003,2004,2005,2006,...,2015,2016,2017,2018,2019,2020,2021,SR,W–L,Win %
0,Grand Slam tournaments,,,,,,,,,,...,,,,,,,,,,
1,Australian Open,A,Q1,3R,3R,4R,4R,W,SF,W,...,,,,,,,,,,
2,French Open,A,1R,4R,QF,1R,1R,3R,SF,F,...,,,,,,,,,,
3,Wimbledon,A,1R,1R,QF,1R,W,W,W,W,...,,,,,,,,,,
4,US Open,A,Q2,3R,4R,4R,4R,W,W,W,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Outdoor W–L,0–1,1–10,15–20,28–13,34–15,55–13,63–5,66–3,75–5,...,,,,,,,,,,
68,Indoor W–L,2–2,12–7,21–10,21–8,24–7,23–4,11–1,15–1,17–0,...,,,,,,,,,,
69,Overall W–L4,2–3,13–17,36–30,49–21,58–22,78–17,74–6,81–4,92–5,...,,,,,,,,,,
70,Win (%),40%,43%,55%,70%,73%,82%,93%,95%,95%,...,,,,,,,,,,
71,Year-end ranking,301,64,29,13,6,2,1,1,1,...,,,,,,,,,,

In [ ]:
# Exportar el DataFrame a un archivo Excel
df.to_excel("federer_stats.xlsx", index=False)